// flow-typed signature: bd0a0afe79861a426268ad25efc09eed
// flow-typed version: <<STUB>>/left-pad_v^1.1.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'left-pad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'left-pad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'left-pad/perf/es6Repeat' {
  declare module.exports: any;
}

declare module 'left-pad/perf/O(n)' {
  declare module.exports: any;
}

declare module 'left-pad/perf/perf' {
  declare module.exports: any;
}

declare module 'left-pad/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'left-pad/index' {
  declare module.exports: $Exports<'left-pad'>;
}
declare module 'left-pad/index.js' {
  declare module.exports: $Exports<'left-pad'>;
}
declare module 'left-pad/perf/es6Repeat.js' {
  declare module.exports: $Exports<'left-pad/perf/es6Repeat'>;
}
declare module 'left-pad/perf/O(n).js' {
  declare module.exports: $Exports<'left-pad/perf/O(n)'>;
}
declare module 'left-pad/perf/perf.js' {
  declare module.exports: $Exports<'left-pad/perf/perf'>;
}
declare module 'left-pad/test.js' {
  declare module.exports: $Exports<'left-pad/test'>;
}
